### PR TITLE
Added new web core frontend

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves

Resolves safe-global/safe-infrastructure#58

## How this PR fixes it

Added new `web-core` Docker image to use our new UI in [the `docker-compose` file](https://github.com/safe-global/safe-infrastructure/pull/62/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R109).

Updated the [`ui.env` file](https://github.com/safe-global/safe-infrastructure/pull/62/files#diff-06cec2c9c8bd6d55e9b8ea23918ab267d6eec562d89100eb587129f88bb133f1) with the new `web-core` env vars.

Updated [docs](https://github.com/safe-global/safe-infrastructure/pull/62/files#diff-6b60c91204cf14e0fe2fc7e80f79fd16aefd832a2bfb049979a1fc6047d99b2eR87).

## How to test it

follow the instructions defined in the docs to add your chain.

Tested in local used `volta` chain testnet.

1. ### Create the env file:
```
cp .env.sample .env
```

with `volta` chain `RPC_NODE_URL` value:

```
REVERSE_PROXY_PORT=8000
REVERSE_PROXY_UI_PORT=8080

CFG_VERSION=latest
CGW_VERSION=latest
TXS_VERSION=latest

RPC_NODE_URL=https://volta-rpc.energyweb.org

```

2.  ### Create Django superusers in the `config-service` & `transaction-service`
build and run containers by executing

```
docker compose up
```
#### Create `config-service` superuser:
```
docker compose exec cfg-web python src/manage.py createsuperuser --noinput
```
Now you can access `http://localhost:8000/cfg/admin/` and login using the credentials :
```
login: root
pass: admin
```

#### Create `transaction-service` superuser:
```
docker compose exec txs-web python manage.py createsuperuser --username root
```
populate email in the terminal: `example@test.test`
populate pass in the terminal: `admin`

Now you can access `http://localhost:8000/txs/admin` and login using the credentials :
```
login: root
pass: admin
```

3.  ### Add The Chain object definition in the `transaction-service` ( it represents metadata specific to your chain)

Access to the `http://localhost:8000/cfg/admin/chains/chain/add/` and login using the credentials (`root/admin`)

Add your chain with this data (we use `volta` chain data as an example)

Captura de pantalla 2022-12-20 a las 18 23 55
Captura de pantalla 2022-12-20 a las 18 24 28

Note: Remember to edit your `ChainInfo` json fields `transaction_service_uri` and `vpc_transaction_service_uri` to point to your local instance of the transaction service. The values should be `http://nginx:8000/txs`

4. ### Add  Webhooks

Access the admin panel at `http://localhost:8000/txs/admin`,  click the `Add` link for `Web hooks`. Ignore the `Address` field. Set the `Url` field to `http://nginx:8000/cgw/v1/chains/{chainId}/hooks/events` and replace `{chainId}` with the corresponding chainId. Set the `Authorization` field to `Basic <WEBHOOK_TOKEN>`, where `<WEBHOOK_TOKEN>` corresponds to the value of `WEBHOOK_TOKEN` in the `container_env_files/cgw.env` file of this repository (in my case I just keep the `some_random_token` default value):

Captura de pantalla 2022-12-20 a las 18 44 29

5. ### tests the UI
The Safe Web app will be available at at `http://localhost:8080`

## Screenshots

Captura de pantalla 2022-12-20 a las 17 25 51
Captura de pantalla 2022-12-20 a las 17 25 56
Captura de pantalla 2022-12-20 a las 17 26 24
Captura de pantalla 2022-12-20 a las 17 28 06
Captura de pantalla 2022-12-20 a las 17 29 20

- [X]  pending from web-core team to merge [the updated Dockerfile PR](https://github.com/safe-global/web-core/pull/1408).
- [x] pending from infra team to deploy the `safeglobal/web-core` image to our `safeglobal` docker hub
- [ x]  Waiting for a `safeglobal/web-core:latest` image.

Captura de pantalla 2022-12-23 a las 15 07 22

### CODE REVIEW

**Comment by DaniSomoza** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DaniSomoza** [comment]
recheck

**Comment by DaniSomoza** [comment]
NOTE: pending from web-core team to merge https://github.com/safe-global/web-core/pull/1408.

NOTE: pending from infra team to deploy the safeglobal/web-core image to our safeglobal docker hub

**Comment by DaniSomoza** [comment]
Hi @Uxio0 ! It seems that its ready to be merged! 🚀

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
